import type { Metadata, Viewport } from 'next'
import localFont from 'next/font/local'
import { Vazirmatn } from 'next/font/google'
import { Analytics } from '@vercel/analytics/next'
import './globals.css'
import { Providers } from '@/components/providers/providers'
import { PreloaderProvider } from '@/components/providers/preloader-provider'

const inter = localFont({
  src: './fonts/InterVariable.ttf',
  variable: '--font-inter',
  display: 'swap',
})

const vazirmatn = Vazirmatn({
  subsets: ['arabic', 'latin'],
  variable: '--font-vazirmatn',
  display: 'swap',
})

const SITE_NAME = 'ArvandSmartControl'
const SITE_DESCRIPTION = 'پلتفرم هوشمند پایش و کنترل چیلر — مانیتورینگ لحظه‌ای، تحلیل مصرف انرژی، تشخیص ناهنجاری و نگهداری پیش‌بینانه برای چیلرهای Carel، Danfoss، Microtech و سایر برندها. بدون نیاز به گیت‌وی، اتصال مستقیم TCP/IP. | Advanced IoT platform for intelligent monitoring, control and management of chiller systems with real-time data analytics, anomaly detection, and predictive maintenance.'
const BASE_URL = 'https://arvandsmart.com'

export const metadata: Metadata = {
  title: {
    default: `ArvandSmartControl | پلتفرم هوشمند پایش و کنترل چیلر`,
    template: `%s | ArvandSmartControl`,
  },
  description: SITE_DESCRIPTION,
  metadataBase: new URL(BASE_URL),
  alternates: {
    canonical: BASE_URL,
    languages: {
      fa: BASE_URL,
      en: `${BASE_URL}/en`,
      ar: `${BASE_URL}/ar`,
    },
  },
  openGraph: {
    type: 'website',
    locale: 'fa_IR',
    alternateLocale: ['en_US', 'ar_SA'],
    siteName: SITE_NAME,
    title: `ArvandSmartControl | پلتفرم هوشمند پایش و کنترل چیلر`,
    description: SITE_DESCRIPTION,
    url: BASE_URL,
    // OG image is auto-generated by app/opengraph-image.tsx (next/og)
  },
  twitter: {
    card: 'summary_large_image',
    title: `ArvandSmartControl | پلتفرم هوشمند پایش و کنترل چیلر`,
    description: SITE_DESCRIPTION,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  keywords: [
    'سیستم مانیتورینگ چیلر',
    'کنترل هوشمند چیلر',
    'پایش لحظه‌ای چیلر',
    'مدیریت انرژی ساختمان',
    'بهینه‌سازی مصرف انرژی',
    'سیستم مدیریت ساختمان BMS',
    'اینترنت اشیاء ساختمان',
    'نگهداری پیش‌بینانه چیلر',
    'کنترلر کارل pCO',
    'chiller monitoring',
    'HVAC control system',
    'IoT building management',
    'smart chiller controller',
    'energy optimization',
    'predictive maintenance',
    'BMS system',
    'building automation',
  ],
  category: 'technology',
  classification: 'IoT & Building Management',
  other: {
    'google-site-verification': process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION || '',
  },
}

export const viewport: Viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#faf8f5' },
    { media: '(prefers-color-scheme: dark)', color: '#030712' },
  ],
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fa" suppressHydrationWarning className="bg-background">
      <head>
        {/* JSON-LD Structured Data */}
        <script
          type="application/ld+json"
          suppressHydrationWarning
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              '@context': 'https://schema.org',
              '@type': 'Organization',
              name: SITE_NAME,
              alternateName: ['Arvand Smart Control', 'اروند اسمارت کنترل'],
              url: BASE_URL,
              logo: `${BASE_URL}/logo.png`,
              description: SITE_DESCRIPTION,
              foundingDate: '2020',
              contactPoint: {
                '@type': 'ContactPoint',
                telephone: '+98-21-12345678',
                contactType: 'customer service',
                availableLanguage: ['English', 'Persian', 'Arabic'],
              },
              sameAs: [
                'https://linkedin.com/company/arvandsmart',
                'https://instagram.com/arvandsmart',
              ],
              offers: {
                '@type': 'AggregateOffer',
                offerCount: '3',
                availability: 'https://schema.org/InStock',
              },
            }),
          }}
        />
        {/* WebSite schema */}
        <script
          type="application/ld+json"
          suppressHydrationWarning
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              '@context': 'https://schema.org',
              '@type': 'WebSite',
              name: SITE_NAME,
              url: BASE_URL,
              description: SITE_DESCRIPTION,
              inLanguage: ['fa', 'en', 'ar'],
              potentialAction: {
                '@type': 'SearchAction',
                target: {
                  '@type': 'EntryPoint',
                  urlTemplate: `${BASE_URL}/search?q={search_term_string}`,
                },
                'query-input': 'required name=search_term_string',
              },
            }),
          }}
        />
        {/* BreadcrumbList schema */}
        <script
          type="application/ld+json"
          suppressHydrationWarning
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              '@context': 'https://schema.org',
              '@type': 'BreadcrumbList',
              itemListElement: [
                { '@type': 'ListItem', position: 1, name: 'Home', item: BASE_URL },
                { '@type': 'ListItem', position: 2, name: 'Products', item: `${BASE_URL}/#products` },
                { '@type': 'ListItem', position: 3, name: 'Blog', item: `${BASE_URL}/blog` },
              ],
            }),
          }}
        />
        {/* FAQ schema */}
        <script
          type="application/ld+json"
          suppressHydrationWarning
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              '@context': 'https://schema.org',
              '@type': 'FAQPage',
              mainEntity: [
                {
                  '@type': 'Question',
                  name: 'آیا به گیت‌وی یا سخت‌افزار اضافی نیاز دارم؟',
                  acceptedAnswer: {
                    '@type': 'Answer',
                    text: 'خیر. ArvandSmartControl مستقیماً از طریق TCP/IP به کنترلرهای چیلر شما متصل می‌شود. بدون گیت‌وی، بدون سخت‌افزار اضافه، بدون دردسر تنظیمات. کافیست کنترلر خود را به شبکه وصل کنید و آنلاین شوید.',
                  },
                },
                {
                  '@type': 'Question',
                  name: 'کدام برندها و کنترلرهای چیلر پشتیبانی می‌شوند؟',
                  acceptedAnswer: {
                    '@type': 'Answer',
                    text: 'ما از Carel (سری pCO)، Danfoss (MCX, EKF)، Microtech (UC, EC)، Siemens (Climatix, Synco)، Honeywell (Spyder, WEB)، Johnson Controls (Metasys, FX)، Schneider (EcoStruxure) و LG (Multi V, VRF) پشتیبانی می‌کنیم. اگر کنترلر شما Modbus، BACnet یا TCP/IP پشتیبانی می‌کند، کار خواهد کرد.',
                  },
                },
                {
                  '@type': 'Question',
                  name: 'نصب چقدر طول می‌کشد؟',
                  acceptedAnswer: {
                    '@type': 'Answer',
                    text: 'بیشتر نصب‌ها در ۲-۴ ساعت برای هر سایت تکمیل می‌شوند. برای یک تأسیسات معمولی با ۵-۱۰ چیلر، کل راه‌اندازی شامل تنظیمات کمتر از یک روز طول می‌کشد. تیم ما همه چیز را از راه دور انجام می‌دهد — بدون نیاز به حضور در محل.',
                  },
                },
                {
                  '@type': 'Question',
                  name: 'اگر اتصال اینترنت من قطع شود چه اتفاقی می‌افتد؟',
                  acceptedAnswer: {
                    '@type': 'Answer',
                    text: 'چیلرهای شما به طور عادی به کار خود ادامه می‌دهند — ArvandSmartControl یک پلتفرم نظارت و بهینه‌سازی است، نه یک سیستم کنترل حیاتی. داده‌ها به صورت محلی ذخیره و هنگام بازگشت اتصال به طور خودکار همگام‌سازی می‌شوند. هرگز داده‌های تاریخی را از دست نخواهید داد.',
                  },
                },
                {
                  '@type': 'Question',
                  name: 'آیا داده‌های من امن هستند؟',
                  acceptedAnswer: {
                    '@type': 'Answer',
                    text: 'بله. تمام داده‌ها در حال انتقال (TLS 1.3) و در حالت ذخیره (AES-256) رمزنگاری می‌شوند. ما مطابق با SOC 2 هستیم و از بهترین روش‌های صنعت برای کنترل دسترسی و ثبت رویدادها پیروی می‌کنیم.',
                  },
                },
                {
                  '@type': 'Question',
                  name: 'آیا می‌توانم قبل از خرید امتحان کنم؟',
                  acceptedAnswer: {
                    '@type': 'Answer',
                    text: 'حتماً. ما یک دوره آزمایشی رایگان ۱۴ روزه با دسترسی کامل به همه امکانات ارائه می‌دهیم — بدون نیاز به کارت اعتباری. یک محیط دمو متصل به چیلرهای شما راه‌اندازی می‌کنیم تا نتایج را از نزدیک ببینید.',
                  },
                },
                {
                  '@type': 'Question',
                  name: 'آیا می‌توانم داشبورد را با برند شرکت خود شخصی‌سازی کنم؟',
                  acceptedAnswer: {
                    '@type': 'Answer',
                    text: 'بله. پلن سازمانی ما شامل شخصی‌سازی کامل برند سفید است — دامنه اختصاصی، لوگوی شرکت، رنگ‌های برند و چیدمان داشبورد سفارشی. پلتفرم با هویت سازمان شما تطبیق می‌یابد، نه برعکس.',
                  },
                },
                {
                  '@type': 'Question',
                  name: 'چه نوع پشتیبانی ارائه می‌دهید؟',
                  acceptedAnswer: {
                    '@type': 'Answer',
                    text: 'همه پلن‌ها شامل پشتیبانی ایمیلی با زمان پاسخ ۴ ساعت هستند. پلن حرفه‌ای پشتیبانی اولویت‌دار با پاسخ ۱ ساعته اضافه می‌کند. پلن سازمانی شامل مدیر حساب اختصاصی و پشتیبانی تلفنی ۲۴/۷ است.',
                  },
                },
              ],
            }),
          }}
        />
        {/* Product schema */}
        <script
          type="application/ld+json"
          suppressHydrationWarning
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              '@context': 'https://schema.org',
              '@type': 'Product',
              name: 'ArvandSmartControl — Intelligent Chiller Monitoring Platform',
              description: 'Advanced IoT platform for intelligent monitoring, control and management of chiller systems with real-time data analytics, anomaly detection, and predictive maintenance capabilities.',
              brand: { '@type': 'Brand', name: 'ArvandSmartControl' },
              offers: [
                {
                  '@type': 'Offer',
                  name: 'Starter',
                  description: 'For small facilities and single-site monitoring. Up to 5 chillers, real-time monitoring, email alerts, 7-day history.',
                  price: '49000000',
                  priceCurrency: 'IRR',
                  priceSpecification: {
                    '@type': 'UnitPriceSpecification',
                    billingDuration: 'P1M',
                  },
                  eligibleQuantity: { '@type': 'QuantitativeValue', value: 5, unitText: 'chillers' },
                },
                {
                  '@type': 'Offer',
                  name: 'Professional',
                  description: 'For growing operations with multiple sites. Up to 25 chillers, advanced analytics, predictive maintenance, API access.',
                  price: '399000000',
                  priceCurrency: 'IRR',
                  priceSpecification: {
                    '@type': 'UnitPriceSpecification',
                    billingDuration: 'P1Y',
                  },
                  eligibleQuantity: { '@type': 'QuantitativeValue', value: 25, unitText: 'chillers' },
                },
                {
                  '@type': 'Offer',
                  name: 'Enterprise',
                  description: 'Custom solutions for large-scale deployments. Unlimited chillers, custom integrations, dedicated account manager, white-label option.',
                  price: '0',
                  priceCurrency: 'IRR',
                },
              ],
              aggregateRating: {
                '@type': 'AggregateRating',
                ratingValue: '4.8',
                bestRating: '5',
                ratingCount: '127',
                reviewCount: '127',
              },
            }),
          }}
        />
        {/* PWA manifest */}
        <link rel="manifest" href="/manifest.json" />
        {/* Preconnect to critical origins */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        {/* DNS prefetch for analytics */}
        <link rel="dns-prefetch" href="https://vercel.com" />
      </head>
      <body
        className={`${inter.variable} ${vazirmatn.variable} font-sans antialiased bg-background text-foreground`}
      >
        <Providers>
          <PreloaderProvider>{children}</PreloaderProvider>
        </Providers>
        {process.env.NODE_ENV === 'production' && <Analytics />}
      </body>
    </html>
  )
}
